---
- name: apk | Updating apt cache
  apk:
    update_cache: "yes"
  tags: packages

- name: apk | Installing packages
  apk:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages }}"
  tags: packages
