---
- name: apt | Adding apt key for repository
  apt_key:
    url: "{{ item.key }}"
    state: present
  when: not(item.key is undefined or item.key is none or item.key|trim == '')
  with_items: "{{ repositories|default(packages_repositories_apt) }}"
  tags: packages

- name: apt | Adding apt repository
  apt_repository:
    repo: "{{ item.url }}"
    state: present
  with_items: "{{ repositories|default(packages_repositories_apt) }}"
  tags: packages

- name: apt | Updating apt cache
  apt:
    update_cache: "yes"
  tags: packages

- name: apt | Installing apt packages
  apt:
    pkg: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages|default(packages_list_apt) }}"
  tags: packages
