---
- debug:
    var: ansible_pkg_mgr
# Install apt packages and repositories
- import_tasks: apt.yml
  when: ansible_pkg_mgr == "apt"

# Install yum packages and repositories
- import_tasks: yum.yml
  when: ansible_pkg_mgr == "yum"

# Install yum packages and repositories
- import_tasks: apk.yml
  when: ansible_pkg_mgr == "apk"
