---
- name: yum | Adding yum repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(item.name) }}"
    baseurl: "{{ item.baseurl | default('') }}"
    mirrorlist: "{{ item.mirrorlist | default('') }}"
    enabled: "{{ item.enabled | default('yes') }}"
    gpgcheck: "{{ item.gpgcheck | default('no') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages_repositories|default(packages_repositories_yum) }}"
  tags:
    - packages
    - repository

- name: yum | Installing yum packages
  yum:
    pkg: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages|default(packages_list_yum) }}"
  tags:
    - packages
    - install
